var nameList = [
  "Aarav",
  "Aarushi",
  "Aashi",
  "Abhinav",
  "Aditi",
  "Aditya",
  "Advait",
  "Ahana",
  "Aisha",
  "Aishwarya",
  "Akansha",
  "Akash",
  "Akshara",
  "Akshay",
  "Alok",
  "Amit",
  "Amrita",
  "Amritsar",
  "Anamika",
  "Ananya",
  "Anaya",
  "Aniket",
  "Anisha",
  "Anita",
  "Ankush",
  "Anmol",
  "Ansh",
  "Anushka",
  "Anya",
  "Aparna",
  "Arnav",
  "Arpita",
  "Arjun",
  "Arohi",
  "Arun",
  "Arvind",
  "Aryan",
  "Asha",
  "Ashish",
  "Ashok",
  "Asmita",
  "Avinash",
  "Ayush",
  "Bhavesh",
  "Bhavya",
  "Bhumika",
  "Brijesh",
  "Chaitanya",
  "Chandan",
  "Chandni",
  "Charulata",
  "Chetan",
  "Chhavi",
  "Chirag",
  "Daksh",
  "Daman",
  "Damini",
  "Darshana",
  "Deepti",
  "Devesh",
  "Dhruv",
  "Diksha",
  "Dinesh",
  "Divya",
  "Ekta",
  "Firoz",
  "Garima",
  "Gaurav",
  "Geeta",
  "Girish",
  "Gitika",
  "Gopal",
  "Gowri",
  "Gulab",
  "Guna",
  "Guru",
  "Hansraj",
  "Harish",
  "Harsha",
  "Harshita",
  "Hemant",
  "Himani",
  "Hina",
  "Hitesh",
  "Ishani",
  "Ishita",
  "Ishwar",
  "Jagdish",
  "Jai",
  "Jaideep",
  "Jaishree",
  "Jasmine",
  "Jatin",
  "Jay",
  "Jayant",
  "Jeevan",
  "Jyoti",
  "Kajal",
  "Kamal",
  "Kamlesh",
  "Kanchan",
  "Kanika",
  "Karan",
  "Kartikeya",
  "Karuna",
  "Kavita",
  "Ketan",
  "Khushbu",
  "Kiran",
  "Kirti",
  "Krishna",
  "Kunal",
  "Kusum",
  "Lalit",
  "Lata",
  "Lavanya",
  "Laxmi",
  "Madhav",
  "Madhuri",
  "Mahendra",
  "Mahesh",
  "Mahima",
  "Mala",
  "Manish",
  "Manisha",
  "Manoj",
  "Meenakshi",
  "Megha",
  "Mehul",
  "Mihir",
  "Mitali",
  "Mohan",
  "Mohini",
  "Monika",
  "Mukesh",
  "Mukul",
  "Nakul",
  "Namita",
  "Neha",
  "Nidhi",
  "Nikhil",
  "Nilesh",
  "Nisha",
  "Nitin",
  "Nupur",
  "Om",
  "Padma",
  "Pallavi",
  "Pankaj",
  "Parul",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

var comments = [
  "Great content!🚀🚀",
  "Loving this live stream!",
  "Awesome video!",
  "Keep it up!🚀🚀",
  "Thanks for sharing!",
  "I'm learning so much from this!",
  "This is amazing!",
  "I'm enjoying every minute of it!",
  "Can't wait for the next live stream!",
  "You're doing a fantastic job!",
  "So informative!🚀🚀",
  "Jai Shree Ram 🚩🚩🚩",
  "Jai Shree Ram 🚩🚩🚩",

  "This is gold!",
  "Mind blown!🚀🚀",
  "I'm taking notes!",
  "You're killing it!",
  "So helpful!",
  "This is exactly what I needed!",
  "I've been waiting for this live stream!",
  "Brilliant 🚀🚀!",
  "I'm so inspired!",
  "You're a rockstar!",
  "I'm learning new things!",
  "Thank you for doing this!",
  "I'm getting so many insights!",
  "I'm hooked!🚀🚀",
  "Jai Shree Ram 🚩🚩🚩",
  "I'm so grateful for this live stream!",
  "You're changing lives!",
  "Incredible!",
  "So engaging!🚀🚀",
  "Jai Shree Ram 🚩🚩🚩",
  "I'm loving the Q&A!",
  "You're a wealth of knowledge!",
  "This is life-changing!",
  "I'm in awe! 🚀🚀",
  "You're making a difference!",
  "I can't get enough of this!",
  "I'm so motivated!",
  "This is pure gold!",
  "I'm getting so many ideas!",
  "You're an inspiration!",
  "This is epic! 🚀🚀",
  "I'm loving the interaction!",
  "So valuable!",
  "You're the best!🚀🚀",
  "This is game-changing!",
  "I'm so impressed!",
  "You're a genius!🚀🚀",
  "I'm on the edge of my seat!",
  "I'm taking action right away!",
  "You're a game-changer!",
  "This is next level!",
  "I'm so glad I joined this live stream!",
  "You're a true expert!",
  "I'm learning so much from your experience!",
  "This is top-notch!",
  "You're making it look so easy!",
  "I'm so motivated to take action!",
  "You're a master at what you do!",
  "This is eye-opening!",
  "I'm loving the energy!",
  "You're giving so much value!",
  "I'm so grateful for this opportunity!",
  "This is mind-blowing!",
  "I'm getting so many ideas for my business!",
  "You're a true professional!",
  "I'm so excited!🚀🚀",
  "This is exactly what I needed to hear!",
  "You're changing the game!",
  "I'm learning new strategies!",
  "This is so inspiring!",
  "You're a role model!",
  "I'm so impressed with your knowledge!",
  "This is invaluable!",
  "You're a true mentor!",
  "I'm loving the tips and tricks!",
  "You're a game-changer in the industry!",
  "This is pure awesomeness!",
  "I'm taking so many notes!",
  "You're making a huge impact!",
  "I'm so lucky to be a part of this live stream!",
  "This is gold for my business!",
  "You're sharing so much wisdom!",
  "I'm so grateful for your insights!",
  "This is so helpful for my goals!",
  "You're an authority in your field!",
  "I'm so motivated to take action!",
  "This is so practical!",
  "You're a true leader!",
  "I'm learning from the best!",
  "This is life-changing advice!",
  "You're a true inspiration!",
  "I'm loving the real-world examples!",
  "This is exactly what I needed!",
  "You're a true guru!",
  "Great live stream, thanks for sharing!",
  "Loving the content, keep it up!",
  "Can't wait to see what's next in the stream!",
  "This is awesome! You guys are killing it!",
  "I'm learning so much from this stream, thank you!",
  "The quality of the video is amazing, great job!",
  "Wow, I never knew this before. Thanks for sharing!",
  "This is so interesting, I'm hooked!",
  "I'm loving the energy of this live stream!",
  "The community here is amazing, I'm glad I joined!",
];
export function generateRandomComment() {
  return comments[Math.floor(Math.random() * comments.length)];
}
var profiles = [
  "https://yt4.ggpht.com/uji7OaPdPb9fdooaiPaXprODc6rQhBBLFoKHeK48XyJUFGjVWjotKR4pgoZyEtSYEebBhjGisg=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/ytc/AGIKgqPZmZV8UCz_JkD_3ZyLQYv7fmBaKUIaP2fBgTpBLQ=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/2Zd7YLikil7kcaldKXv9EvQlIRN3OG_Ptxy3lHds9EJBguN2gkFE-izK8fL3fJhrRL3NfqlVHQ=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/ytc/AGIKgqMHfC7qJq8HK0hhzX8Y82UQw86dwVQigHE2D-NQGQ=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/po7MLropHdZvEizW_vryoqQDAgX7LBZ-djsApKzE3roFi1Y-e0jPOlDac30NLUbK3H7w3J9K=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/ytc/AGIKgqP5VQbJBsYyK6r60H1jY1dwfuV4esfPuXd7CZ1qMw=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/ytc/AGIKgqMdvLp_gg_vGCvKaPV5Hj5SP6aobmZ417WSsqfb=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/2aBkyHw69O8UqUp-PuMlFhLdgEOadrgUiZT2lneUNLGXRAs4p12MatR5tctdRdjjT4hikb7MQN4=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/ytc/AGIKgqN7ymaaPrVa6SmIRccCqRg732FCc2yt9f4QV9rP=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/rifUswZJYVjGipAZ9769EckqGU13MlP1C0pAJY1aDPH9r5HNxRargkLZ0flZl3Cx49NsNrDEgpI=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/ytc/AGIKgqNsjRjwbPV3aU_7kkOkDNSC43tvaHVQk2b02e0M8Q=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/L6wGc_2ICGJPaGX4dxpApy_hXOEdqhLkuDa0o36Kkki1wLHADO0HslUidbfxsDEo8w662cS6teg=s32-c-k-c0x00ffffff-no-rj",
  "https://yt4.ggpht.com/ytc/AGIKgqNmHhTsCc22i-QgLkI7Dcemq0hXebB4Qpxb-4jUWaE=s32-c-k-c0x00ffffff-no-rj",
];
export function generateProfile() {
  return profiles[Math.floor(Math.random() * profiles.length)];
}

export const LIVE_CHAT_OFFSET = 22;
